name: plumber
channels:
  - pkgw-forge
  - conda-forge
  - defaults
dependencies:
  - astroplan
  - astropy>=5.2.1
  - casa-data
  - click>=8.1.3
  - matplotlib
  - numpy
  - pandas>=1.5.2
  - pip
  - python=3.8
  - scipy
  - setuptools
  - pip:
    - casa-formats-io
    - casadata
    - casatasks
    - casatools
    - dask
    - plumber
    - pyproject-toml
    - spectral-cube
