[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "xtensor"
version = "0.24.6"
description = "C++ tensors with broadcasting and lazy computing"
keywords = ["c-plus-plus", "tensor", "numpy", "array"]
readme = "README.md"
license = {text = "GPL-3.0 license"}

[tool.scikit-build]
wheel.py-api = "py3"
wheel.install-dir = "xtensor"
wheel.expand-macos-universal-tags = false